# Generated by Django 5.2.4 on 2025-07-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0002_app_date_added_app_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
