# Generated by Django 5.2.4 on 2025-07-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0005_alter_chaireview_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='locaiont',
            new_name='location',
        ),
    ]
